ALTER TABLE "Room" ADD COLUMN "minPlayersToStart" INTEGER NOT NULL DEFAULT 2;
ALTER TABLE "Room" ADD COLUMN "ante" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Room" ADD COLUMN "actionTimeoutSeconds" INTEGER NOT NULL DEFAULT 30;
ALTER TABLE "Room" ADD COLUMN "creatorOnlyStart" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Hand" ADD COLUMN "ante" INTEGER NOT NULL DEFAULT 0;
