// Auto-generated by scripts/generate-sound-manifest.mjs — do not edit manually
// Generated at 2026-06-10T17:39:54.553Z
export const AVAILABLE_SOUNDS = ["allin","bet","call","fold","raise","turn","win"] as const;
export type AvailableSound = (typeof AVAILABLE_SOUNDS)[number];
