// Auto-generated by scripts/generate-sound-manifest.mjs — do not edit manually
// Generated at 2026-06-09T14:16:11.854Z
export const AVAILABLE_SOUNDS = ["allin","bet","call","fold","raise","turn","win"] as const;
export type AvailableSound = (typeof AVAILABLE_SOUNDS)[number];
